/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer */

#ifndef _Included_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
#define _Included_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_NOP
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_NOP 0L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_PREPARED
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_PREPARED 1L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_PLAYBACK_COMPLETE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_PLAYBACK_COMPLETE 2L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_BUFFERING_UPDATE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_BUFFERING_UPDATE 3L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_SEEK_COMPLETE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_SEEK_COMPLETE 4L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_SET_VIDEO_SIZE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_SET_VIDEO_SIZE 5L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR 100L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO 200L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_UNKNOWN
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_UNKNOWN 1L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_SERVER_DIED
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_SERVER_DIED 100L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK 200L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_UNKNOWN
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_UNKNOWN 1L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_VIDEO_TRACK_LAGGING
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_VIDEO_TRACK_LAGGING 700L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_BAD_INTERLEAVING
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_BAD_INTERLEAVING 800L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_NOT_SEEKABLE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_NOT_SEEKABLE 801L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_METADATA_UPDATE
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_METADATA_UPDATE 802L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_FRAMERATE_VIDEO
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_FRAMERATE_VIDEO 900L
#undef cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_FRAMERATE_AUDIO
#define cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_MEDIA_INFO_FRAMERATE_AUDIO 901L
/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1getVersion
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1setDataSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_prepare
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1prepare
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_prepareAsync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1prepareAsync
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1start
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1stop
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1pause
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_seekTo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1seekTo
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1release
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1reset
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_getVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1getVideoWidth
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1getVideoHeight
  (JNIEnv *, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_invoke
 * Signature: (Landroid/os/Parcel;Landroid/os/Parcel;)I
 */
JNIEXPORT jint JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1invoke
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_setParameter
 * Signature: (ILandroid/os/Parcel;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1setParameter
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_setVideoSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1setVideoSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayer_native_1finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
