/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayerJNI */

#ifndef _Included_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayerJNI
#define _Included_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayerJNI
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_whaley_sh_mediaplayer_FFMediaPlayer_FFMediaPlayerJNI_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
